### ISSUE TITLE
Bugs in saved data

### ISSUE THREAD

**Issue by Shashank3736** [TrueXPixels/quick.db-docs#4]
Yahh I encountered a bug in quick.db, Whenever you restart your bot several times in a time interval of 5-10min the database becomes corrupted and do not provide the date you want. For e.g. I set up a prefix system. It works fine in starting but once I restarted the bot almost 5 times in a row(to fix an error) it stops working I need to again set up a prefix for the server(we have a global prefix @client.user.tag) and then bot works fine with the prefix.

Note: it works fine in my other projects which restarts like 1-2 times in a day or less.

**Comment by lorencerri** [comment]
If you're still experiencing this issue, please submit an issue at https://github.com/plexidev/quick.db
